version: '3.7'
services:
  mongo:
    image: mongo:5.0.4
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017
    restart: unless-stopped     
    command: mongod --logpath=/dev/null # --quiet

  rabbitmq:
    image: "rabbitmq:3.9.9-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "0eaf0f4e-7078-44b0-970d-1c3d1277f9f2"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "${RABBITMQ_EXT_PORT}:15672"
      - "${RABBITMQ_ADM_EXT_PORT}:5672"
    labels:
      NAME: "rabbitmq"
    restart: unless-stopped  
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

