fileStorage:
    path: local-fs/in

mongo:
    url: mongodb://tts:---@localhost:27018

messageServer:
    url: localhost:5673/
    user: tts
    pass: ---

splitter:
    inTemplate: ../upload/local-fs/in/{}.txt
    outTemplate: ../upload/local-fs/work/{}/split

synthesizer:
    url: https://sinteze.intelektika.lt/synthesis.service/astra/synthesize
    outTemplate: ../upload/local-fs/work/{}/audio

joiner:
    outTemplate: ../upload/local-fs/work/{}/result
    workTemplate: ../upload/local-fs/work/{}/
    metadata:
        - copyright=UAB Intelektika
        - description=encoded by UAB Intelektika
