port: 8182

fileStorage:
    path: ../upload/local-fs
    patterns:
        - in/{ID}.txt
        - work/{ID}/
timer:
    runEvery: 1m        
    expire: 1h        
mongo:
    url: mongodb://tts:---@localhost:27018  
